export const GenreListArray = [
    {id: 0, name: 'all'},
    {id: 1, name: 'action'},
    {id: 2, name: 'comedy'},
    {id: 3, name: 'science fiction'},
    {id: 4, name: 'crime'},
    {id: 5, name: 'adventure'}
];

export const SortControlArray = [
    {id: 0, name: 'Release Date'},
    {id: 1, name: 'Title'}
];

export const movieTilesArray = [
    {
        name: "The Shawshank Redemption",
        releaseYear: "1994",
        "Rated": "R",
        "Released": "14 Oct 1994",
        duration: "142 min",
        genres: "Drama",
        "Director": "Frank Darabont",
        "Writer": "Stephen King, Frank Darabont",
        "Actors": "Tim Robbins, Morgan Freeman, Bob Gunton",
        description: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
        "Language": "English",
        "Country": "United States",
        "Awards": "Nominated for 7 Oscars. 21 wins & 43 nominations total",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
        "Ratings": [{"Source": "Internet Movie Database", "Value": "9.3/10"}, {
            "Source": "Rotten Tomatoes",
            "Value": "91%"
        }, {"Source": "Metacritic", "Value": "81/100"}],
        "Metascore": "81",
        imdbRating: "9.3",
        "imdbVotes": "2,559,562",
        "imdbID": "tt0111161",
        "Type": "movie",
        "DVD": "21 Dec 1999",
        "BoxOffice": "$28,767,189",
        "Production": "N/A",
        "Website": "N/A",
        "Response": "True"
    },
    {
        name: "The Godfather",
        releaseYear: "1972",
        "Rated": "R",
        "Released": "24 Mar 1972",
        duration: "175 min",
        genres: "Crime, Drama",
        "Director": "Francis Ford Coppola",
        "Writer": "Mario Puzo, Francis Ford Coppola",
        "Actors": "Marlon Brando, Al Pacino, James Caan",
        description: "The aging patriarch of an organized crime dynasty in postwar New York City transfers control of his clandestine empire to his reluctant youngest son.",
        "Language": "English, Italian, Latin",
        "Country": "United States",
        "Awards": "Won 3 Oscars. 31 wins & 30 nominations total",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
        "Ratings": [{"Source": "Internet Movie Database", "Value": "9.2/10"}, {
            "Source": "Rotten Tomatoes",
            "Value": "97%"
        }, {"Source": "Metacritic", "Value": "100/100"}],
        "Metascore": "100",
        imdbRating: "9.2",
        "imdbVotes": "1,765,414",
        "imdbID": "tt0068646",
        "Type": "movie",
        "DVD": "11 May 2004",
        "BoxOffice": "$136,381,073",
        "Production": "N/A",
        "Website": "N/A",
        "Response": "True"
    },
    {
        name: "The Dark Knight",
        releaseYear: "2008",
        "Rated": "PG-13",
        "Released": "18 Jul 2008",
        duration: "152 min",
        genres: "Action, Crime, Drama",
        "Director": "Christopher Nolan",
        "Writer": "Jonathan Nolan, Christopher Nolan, David S. Goyer",
        "Actors": "Christian Bale, Heath Ledger, Aaron Eckhart",
        description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
        "Language": "English, Mandarin",
        "Country": "United States, United Kingdom",
        "Awards": "Won 2 Oscars. 159 wins & 163 nominations total",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg",
        "Ratings": [{"Source": "Internet Movie Database", "Value": "9.1/10"}, {
            "Source": "Rotten Tomatoes",
            "Value": "94%"
        }, {"Source": "Metacritic", "Value": "84/100"}],
        "Metascore": "84",
        imdbRating: "9.1",
        "imdbVotes": "2,528,462",
        "imdbID": "tt0468569",
        "Type": "movie",
        "DVD": "09 Dec 2008",
        "BoxOffice": "$534,987,076",
        "Production": "N/A",
        "Website": "N/A",
        "Response": "True"
    },
    {
        name: "The Godfather: Part II",
        releaseYear: "1974",
        "Rated": "R",
        "Released": "18 Dec 1974",
        duration: "202 min",
        genres: "Crime, Drama",
        "Director": "Francis Ford Coppola",
        "Writer": "Francis Ford Coppola, Mario Puzo",
        "Actors": "Al Pacino, Robert De Niro, Robert Duvall",
        description: "The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.",
        "Language": "English, Italian, Spanish, Latin, Sicilian",
        "Country": "United States",
        "Awards": "Won 6 Oscars. 17 wins & 20 nominations total",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BMWMwMGQzZTItY2JlNC00OWZiLWIyMDctNDk2ZDQ2YjRjMWQ0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
        "Ratings": [{"Source": "Internet Movie Database", "Value": "9.0/10"}, {
            "Source": "Rotten Tomatoes",
            "Value": "96%"
        }, {"Source": "Metacritic", "Value": "90/100"}],
        "Metascore": "90",
        imdbRating: "9.0",
        "imdbVotes": "1,222,153",
        "imdbID": "tt0071562",
        "Type": "movie",
        "DVD": "24 May 2005",
        "BoxOffice": "$47,834,595",
        "Production": "N/A",
        "Website": "N/A",
        "Response": "True"
    },
    {
        name: "12 Angry Men",
        releaseYear: "1957",
        "Rated": "Approved",
        "Released": "10 Apr 1957",
        duration: "96 min",
        genres: "Crime, Drama",
        "Director": "Sidney Lumet",
        "Writer": "Reginald Rose",
        "Actors": "Henry Fonda, Lee J. Cobb, Martin Balsam",
        description: "The jury in a New York City murder trial is frustrated by a single member whose skeptical caution forces them to more carefully consider the evidence before jumping to a hasty verdict.",
        "Language": "English",
        "Country": "United States",
        "Awards": "Nominated for 3 Oscars. 17 wins & 13 nominations total",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BMWU4N2FjNzYtNTVkNC00NzQ0LTg0MjAtYTJlMjFhNGUxZDFmXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg",
        "Ratings": [{"Source": "Internet Movie Database", "Value": "9.0/10"}, {
            "Source": "Rotten Tomatoes",
            "Value": "100%"
        }, {"Source": "Metacritic", "Value": "96/100"}],
        "Metascore": "96",
        imdbRating: "9.0",
        "imdbVotes": "756,234",
        "imdbID": "tt0050083",
        "Type": "movie",
        "DVD": "04 Mar 2008",
        "BoxOffice": "N/A",
        "Production": "N/A",
        "Website": "N/A",
        "Response": "True"
    },
    {
        name: "Schindler's List",
        releaseYear: "1993",
        "Rated": "R",
        "Released": "04 Feb 1994",
        duration: "195 min",
        genres: "Biography, Drama, History",
        "Director": "Steven Spielberg",
        "Writer": "Thomas Keneally, Steven Zaillian",
        "Actors": "Liam Neeson, Ralph Fiennes, Ben Kingsley",
        description: "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
        "Language": "English, Hebrew, German, Polish, Latin",
        "Country": "United States",
        "Awards": "Won 7 Oscars. 91 wins & 49 nominations total",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
        "Ratings": [{"Source": "Internet Movie Database", "Value": "8.9/10"}, {
            "Source": "Rotten Tomatoes",
            "Value": "98%"
        }, {"Source": "Metacritic", "Value": "94/100"}],
        "Metascore": "94",
        imdbRating: "8.9",
        "imdbVotes": "1,307,427",
        "imdbID": "tt0108052",
        "Type": "movie",
        "DVD": "12 Feb 2008",
        "BoxOffice": "$96,898,818",
        "Production": "N/A",
        "Website": "N/A",
        "Response": "True"
    }
]




